### ISSUE TITLE
Replace slack bridge bot

### ISSUE THREAD

**Issue by axk4545** [RITlug/tasks#48] opened 2018-06-03 17:09 UTC
In a recent update to the bot code that relays messages between IRC and slack, the behavior of the bot changed so that when viewing messages on Slack there is no indication of the IRC side user that sent the message. It appears this may only be an issue when using Slack on mobile.

This is somewhat of an annoyance and it would be nice to remedy it.

**Comment by axk4545** [comment] 2018-06-03 17:09
tagging @Tjzabel since I think he mentioned experiencing it as well.

**Comment by jflory7** [comment] 2018-06-03 17:45
Marking this as `needs info`. Not sure if the issue is with the bot, Slack, or something else. The bot itself hasn't changed nor has it been updated since I began running it. It may be that I need to run a `git pull` to update it.

@axk4545 Could you please attach a screenshot of what you mean? I haven't actually noticed this behavior myself.

**Comment by axk4545** [comment] 2018-06-03 18:42
See attached for screenshot

**Comment by jflory7** [comment] 2018-06-03 23:06
@axk4545 Attachments don't come through via email. Could you drag and drop it into the issue?

**Comment by ct-martin** [comment] 2018-06-10 16:49
Update: This appears to be a change on the Slack client side, we will keep an eye on it

**Comment by ct-martin** [comment] 2018-07-23 00:37
The change in Slack appears to have been reverted, I leave it open to discussion on whether we still want to look into other options or whether we want to close the issue

**Comment by jwflory** [comment] 2018-07-23 16:47
@ct-martin I would make an assumption there was an untested API change and it is probably a fixed bug.

Given the lack of other options, I think it's best to close this as resolved if the original issue with prefixes / names are fixed.

**Closed by jwflory** 2018-07-23 16:47 UTC
Labels: infrastructure, needs info, priority:med
