### ISSUE TITLE
Document CBET servers

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#73] opened 2018-10-01 17:46 UTC
Currently, we know nothing about what these servers are, and what resources they have.

Depending on if there's any sensitive information, there should be a page in either the [runbook](http://runbook.ritlug.com/) or the private infrastructure eboard repo in the [RITlug GitLab](https://git.ritlug.com).

After this documentation exists, it would be much easier to see what can be done with them.

**Comment by ct-martin** [comment] 2018-10-01 19:49
Duplicate of RITlug/runbook#47

**Closed by ct-martin** 2018-10-01 19:49 UTC
Labels: infrastructure, priority:med, projects
