### ISSUE TITLE
Schedule and plan weekly project collaboration meet-ups on weekends across semester

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#39] opened 2018-04-07 17:50 UTC
Some of the other clubs in the Mozilla Open Source Student Network run informal hack sessions / code jams / informal code hours. It would be cool to organize something like this for RITlug on the weekends, something casual and informal. We should discuss this more, but maybe keep it on the backlog until next semester.

h/t @mirdaki @AdrianCollado @bad-science

**Comment by mirdaki** [comment] 2018-04-07 18:05
Hello from the UF Open Source Club! If you have any questions about how we do Casual Coding sessions or why we do them let me know, I'd be happy to help!

**Comment by Tjzabel** [comment] 2018-09-05 20:59
@jwflory I feel this could be a great thing to integrate into FOSS Hours.

**Comment by ct-martin** [comment] 2018-09-05 23:06
While that is a common activity of FOSS Hours, I would like to add that
FOSS Hours is not a RITlug activity (it's under FOSS@MAGIC)

--
Christian Martin (Phone)

**Comment by Tjzabel** [comment] 2018-09-06 00:11
@ct-martin Yep, I'm aware FOSS Hours is not a RITlug activity. It is, however, a much easier and simpler method of introducing casual coding sessions into the FOSS (including RITlug) communy.

**Comment by ct-martin** [comment] 2018-09-07 06:39
@Tjzabel FOSS Hours is not just about casual coding, we also do FOSS Talks and many meetings end up in a discussion rather than the coding we brought with us. I would pitch FOSS Hours to RITlug regardless, but if RITlug is committed to making the original intent as a RITlug event and sometimes to get a hack session done, then I will strongly maintain that FOSS Hours is not the answer to this issue.

**Comment by icflournoy** [comment] 2018-09-24 21:18
### 2018-09-24 Eboard Meeting

#### Action Items
- @jrtechs will work on formalizing the structure of casual coding sessions for the Oct 5th general meeting.

**Comment by Tjzabel** [comment] 2018-09-25 02:28
@jwflory I am actually very +1 to this idea. *Casual Coding Sessions* is a very limiting phrase in what is overall just a general hacking session. This *most definitely* is not just coding, so changing this name to *Project Collaboration Night* makes much more sense, and opens up this opportunity to many more!

**Comment by Bad-Science** [comment] 2018-09-25 20:53
Hello RIT friends!! Love the activity here. I think it's great you are doing casual coding sessions. They have been very successful for us at RCOS. At first the attendance was low but after a semester they are one of our more successful events. I also like the more inclusive name! We had a similar concern about "Casual Coding Sessions" but never came up with anything better 😛 .

@aeksco has been running our casual coding sessions at RCOS and has done a great job with it. He might be able to provide some insight as well 😄

**Comment by aeksco** [comment] 2018-09-26 21:54
We've had a lot of success running weekend sessions on Saturdays and Sundays from 12-4pm - we also have a weekly block set aside on Wednesday evenings from 4-6pm but those typically have been less popular than the weekend sessions

**Comment by Tjzabel** [comment] 2018-09-27 01:04
@aeksco @Bad-Science thanks for the input! We will definitely keep this in mind as we continue ironing out how these "Project Collaboration NIght(s)" are going to work :+1:

**Comment by mirdaki** [comment] 2018-09-27 02:52
Hey all, we at UF have talked a little about a better name, but have the same issue as @Bad-Science (it's just a nice short alliteration). "Project Collaboration Night" sounds good, but only works if you do the event at night haha. I'll ask people again if they have any new ideas ("Casual Collab" maybe?).

@aeksco we have the opposite problem, where are weekday sessions are very popular and weekend events are not. Would you mind describing how you run them (including advertising, how you frame it, what people think about it, etc)?

**Comment by aeksco** [comment] 2018-09-27 16:16
@mirdaki We actually don't do much to promote other than having the sessions count as bonus attendance for students pursuing RCOS for credit. "Bonus" attendance basically enables students to make up absences for required RCOS meetings during the semester - so that's a bit of an incentive, but most students aren't struggling with regular meeting attendance. The sessions are framed as an opportunity for students to work on their RCOS projects and get some closer assistance from mentors.

They're really only promoted to RCOS students, but I'd love to start exploring opportunities that open those events up to students outside of RCOS. We've got a very active subreddit (`/r/rpi`) and I've thought of posting announcements there for events that are open to everyone students.

**Comment by aeksco** [comment] 2018-09-29 20:31
@mirdaki There's not much structure at all - basically a mentor or coordinator finds a decent room with good wifi and people just come and go as they please. Sometimes people ask for help or advice, sometimes people just do homework and hang out. Very "casual" by design

**Comment by mirdaki** [comment] 2018-09-29 22:17
Awesome, thank you for the info @aeksco!

**Comment by jrtechs** [comment] 2018-10-07 15:11
Last Friday (10-5) our casual coding session or "project collaboration night" went pretty well. Attendance was low due to it being the Friday before a long weekend. Although most of us didn't get much work done, I learned a ton about the interests and projects of our club members.

I think that it would be a good idea to promote FOSS hours more in RITlug as being a time to casually work on projects. Within our club it might be worth having more dedicated times to working on projects. The AI club here does weekly project nights at Javas (an on campus coffee shop). I think we should see if people would be interested in meeting at a place like Midnight oil, Artesano, Beans, or Javas (the numerous places to get coffee on RIT) to work on projects. Even if we only get 5 people per week, I think that it would a great opportunity to get people working on club projects.

Another idea that might be fun is seeing if we could get enough people in the club to enter hackathons together.

**Comment by Tjzabel** [comment] 2018-10-07 17:18
@jrtechs With the project collaboration night that happened, I'm wondering how long we should keep this issue up for. We can either leave this up as a reminder to keep this in mind, or close this issue and open another with the goal of trying to include other events that you've mentioned above.

**Comment by jrtechs** [comment] 2018-10-07 17:33
@Tjzabel I say that we keep this issue open until the next eboard meeting where we can discuss what we want to do with casual coding for this semester.

**Comment by jwflory** [comment] 2018-10-07 21:32
> Within our club it might be worth having more dedicated times to working on projects. The AI club here does weekly project nights at Javas (an on campus coffee shop). I think we should see if people would be interested in meeting at a place like Midnight oil, Artesano, Beans, or Javas (the numerous places to get coffee on RIT) to work on projects. Even if we only get 5 people per week, I think that it would a great opportunity to get people working on club projects.

I am totally +1 to this. :+1: I renamed the issue to better reflect what we want to do to close this issue. In our next eboard meeting, I suggest we review date, time, and location, and if on campus, let's try to get it into CampusGroups.

**Comment by icflournoy** [comment] 2018-10-11 13:16
### 2018-10-10 Eboard Meeting

#### Discussion
This sounds like something we want to start doing in November. #64 details the Hacktoberfest meetup which may act as a kickoff for the general project collaboration time.

#### Action Items
- Will discuss at next eboard meeting (2018-10-17) after the Hacktoberfest meetup has been scheduled

**Comment by jwflory** [comment] 2018-10-17 20:33
Discussed as part of #64.

**Comment by icflournoy** [comment] 2018-10-18 20:36
### 2018-10-17 Eboard Meeting
- **action** @jrtechs to plan a longer term schedule and send an email announcement for November/December collaboration meet-ups
- First run of this type of meet-up is the Oct 27th Hacktoberfest event https://github.com/RITlug/tasks/issues/64

**Comment by icflournoy** [comment] 2018-10-25 18:33
### 2018-10-14 Eboard Meeting
- Will discuss at 10/31 eboard meeting after the Hacktoberfest run this weekend

**Comment by icflournoy** [comment] 2018-11-01 12:54
### 2018-10-31 Eboard Meeting
- Learnings from https://github.com/RITlug/tasks/issues/64 should inform our process for weekly collaboration nights going forward

**Comment by jwflory** [comment] 2018-11-04 22:57
We should get another one of these on the calendar at the next eboard meeting.

**Comment by jrtechs** [comment] 2018-11-07 21:32
# Eboard Meeting

Based on attendance of last meet-up, we want to figure out when people are generally available for these events.


## Action Items

@jwflory Will work on figuring out when people are generally available for project collaboration. He will work on this sometime before next eboard meeting.

**Comment by jwflory** [comment] 2018-11-16 02:59
I created a [new WhenIsGood poll](http://whenisgood.net/ritlug/project-jam-nov-dec-2018) to solicit feedback for a good meeting time. Assigning to me and marking as blocked while we wait for responses. I'll work to keep on top of this over the Thanksgiving break.

**Comment by jwflory** [comment] 2018-11-23 19:58
Results from the WhenIsGood are shown [here](http://whenisgood.net/ritlug/project-jam-nov-dec-2018/results/2ias2z3). So far, only me, @ct-martin, and @jrtechs have filled it out. Given next week also has a FOSS Family dinner (#59), I suggest we push our next project session to next semester.

**Comment by Tjzabel** [comment] 2019-02-28 19:46
Closing this due to lack of interest and follow-through.

**Closed by Tjzabel** 2019-02-28 19:46 UTC
Labels: events, priority:med, review at meeting
