### ISSUE TITLE
Fall Semester (2018) Schedule Planning

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#44] opened 2018-05-10 00:38 UTC
Week | Day | Title | Brief | Workshop | Owner
-- | -- | -- | -- | -- | --
01 | Aug. 31 | No Meeting | N/A | N/A | N/A
02 | Sept. 7 | Intro to RITlug | Intro to what the club is about and who the leaders are  | N/A  | @ct-martin @jwflory @jrtechs
03 | Sept. 14 | RITlug: What we do & how to get involved  | What projects are RITlug involved with? Come find out! | N/A | @ct-martin @jrtechs @jwflory 
04 | Sept. 21 | Open Source & How to Do It | Come learn about git and GitHub! | N/A  |  @jwflory @ct-martin  
05 | Sept. 28 | Open Hardware & Raspberry Pis | Learn about open hardware projects, including Raspberry Pis | N/A | @Schneidy
06 | Oct. 5 | Project Collaboration Night | Join us for a night of working with others on personal projects | Yes | @jrtechs 
07 | Oct. 12 | Hacktoberfest | Come learn all about DigitalOcean and GitHub's month-long Hacktoberfest | N/A | @jibby0 
08 | Oct. 19 | Introduction to Containers | This week's presentation will focus on Docker and the general concept of containers | N/A | @icflournoy 
09 | Oct. 26 | Taylor Raspberry pi Talk | Swing on by to learn how to make an augmented Magic Mirror! | N/A | @TaylorBowling
10 | Nov. 2 | RIT Mirrors | Come learn how mirrors work to host packages | N/A | Paul M.
11 | Nov. 9 | Community Talk  | Stay Calm and Carry On | N/A | @cprofitt
12 | Nov 16 | Maker Faire -- general project collab meeting | General Project Meeting | Yes | 
13 | Nov. 23 | Thanksgiving Break  | Thanksgiving Break | N/A  | N/A
14 | Nov.30 | NixOS and Cross-Distro Packaging | An overview of newer cross-distro package systems, snap/flatpak/appimage, as well as Nix/Guix | N/A | @jasoncarr0
15 | Dec. 7 | Final Meeting | Game Night | Yes | @RITlug/eboard-current

**Comment by jwflory** [comment] 2018-08-03 15:08
@jrtechs Since @Tjzabel is not on campus this fall, do you want to take ownership on the first week talk? We'll be happy to help you with this too.

**Comment by jrtechs** [comment] 2018-08-04 11:14
@jwflory Cool, I just updated the schedule to reflect that and our tentative plan from the google doc.

**Comment by jwflory** [comment] 2018-09-18 00:37
_Note_: A more current version of this content is found [on Google Drive](https://docs.google.com/document/d/1-5QrgsyNAyBcbXkKaGckim7qK4rXAk2NYP87GpiQmRM/edit?usp=sharing). It should be converted into this issue when possible.

**Comment by Tjzabel** [comment] 2018-09-18 13:51
@jwflory thanks for the comment. I'm going to update the calendar now

**Comment by ct-martin** [comment] 2018-09-19 16:06
Note: most speakers haven't been confirmed yet

**Comment by Tjzabel** [comment] 2018-09-19 16:19
@ct-martin It may also be a good idea to make a note underneath each of the guest speakers on their confirmation status

**Comment by jasoncarr0** [comment] 2018-09-22 01:08
I'd like to give a talk on package management, snap, flatpak, nix/guix, and co, later in the semester.

**Comment by Tjzabel** [comment] 2018-09-22 02:48
@jasoncarr0 that would be great! Would you like to present *all* of these topics within your one presentation? Looking at our current available meeting times, what date works for you?

Snap and flatpak are super interesting. Let me know what times work for you! Thanks for the interest in giving a presentation! 

If you have any further questions, don't be afraid to come up to one of the eboard members, or comment on this issue.

**Comment by jasoncarr0** [comment] 2018-09-22 02:55
Right, so to some degree I'd like a chance to sell nix, but I'd like to explain the overview. I might have time to give a quick overview of all those topics.
I'm good for a talk, probably after the October 12 slot (unfortunately), so Nov 16th, unless another person drops out.

**Comment by icflournoy** [comment] 2018-09-24 21:18
### 2018-09-24 Eboard Meeting

#### Discussion
- Should we need to promote Hacktoberfest ahead of time? If yes, how?
- Hardware fair, people bring in hardware projects, potential tie-in to source code that can be contributed to for Hacktoberfest

#### Action Items
- @jrtechs planning casual coding session (https://github.com/RITlug/tasks/issues/39) for Oct 5th general meeting.

**Comment by jrtechs** [comment] 2018-10-01 20:19
# Eboard meeting Notes 10-1-18

## Discussion
This Friday we will be having the "project collaboration night" ran by @jrtechs.

## Action Items
@jrtechs Will send out the email for the meeting.
@jibby0 will make the slides/October for the October fest presentation
Confirm graphics talk next Eboard meeting.

**Comment by icflournoy** [comment] 2018-10-11 13:16
### 2018-10-10 Eboard Meeting

#### Discussion
- @ct-martin will not be doing his talk on the 19th
  So what do we do on the 19th?
  @icflournoy can present on Docker if we have a set of slides to use

#### Action Items
- @jrtechs follow up with Taylor (Oct 26th talk), Paul Mezzanini (Nov 2nd talk), and cproffitt (Nov 9th talk) to confirm availability for those dates.
- As soon as we hear back from Taylor/Paul/cproffitt then we can schedule Jason's talk (nixos, packaging), but the talk should be given for eboard before a general meeting.

**Comment by jwflory** [comment] 2018-10-14 16:00
>  @icflournoy can present on Docker if we have a set of slides to use

I'd be willing to pair up on this with you. We should try to decide this before the next eboard meeting so we can get an email out ASAP.

**Comment by icflournoy** [comment] 2018-10-18 20:35
### 2018-10-17 Eboard Meeting
**This week's meeting (10/19)**
- **action** @icflournoy will prepare and send the weekly meeting announcement email
- **action** @icflournoy will review the existing Docker slides, pass to @jwflory sometime Thursday (today)

---

- Taylor confirmed availability for Oct 26th presentation, undecided on topic
- Ccprofitt confirmed availability for Nov 9th presentation, undecided on topic
- Paul Mezzanini is working out scheduling for the Nov 2nd
  - **action** @jrtechs can you give Paul a target date of Oct 26th to let us know the topic?  

- Nov 16th meeting (prior to Maker Faire) we have nothing scheduled
  - Ideqa: How about a projects night that will act as a final check of projects we will be presenting at the Maker Faire.

**Comment by icflournoy** [comment] 2018-10-25 18:33
### 2018-10-14 Eboard Meeting
- **action** @jrtechs to send weekly email, include project collaboration night
- **action** @jrtechs should remind Paul that we'd like his topic by Friday

We're looking at scheduling Jason's NixOS talk for Nov 30th
December 7th most likely would be our last meeting for the semester - Maybe console hacking talks, game day?

**Comment by jrtechs** [comment] 2018-10-26 23:34
We have Paul confirmed for November 2nd

**Comment by jasoncarr0** [comment] 2018-10-27 01:57
I'm good for Nov 30th. And I'd like to, time-permitting, give an overview of Snap/Flatpak/AppImage as well (and likely before I'd talk about Nix/Guix). Sorta "recent developments in packaging"

**Comment by Tjzabel** [comment] 2018-10-27 13:51
@jasoncarr0 awesome! I wish I was able to catch your talk!

**Comment by icflournoy** [comment] 2018-11-01 12:55
### 2018-10-31 Eboard Meeting
- Paul is set for this Friday, we would like confimation that he knows the location/time - @jrtechs to follow up

**Comment by jasoncarr0** [comment] 2018-11-26 20:36
Going to give a talk. Having a bit of trouble coming up with the name. "New developments in packaging" is really boring, so I have "The New Packages" right now, which is pretty mysterious. In any case the description is ultimately something like "An overview of newer cross-distro package systems, snap/flatpak/appimage, as well as Nix/Guix".

**Comment by ct-martin** [comment] 2018-11-26 21:55
"NixOS and Cross-Distro Packaging"?

--
Christian Martin (Phone)

**Comment by icflournoy** [comment] 2018-11-29 12:16
### 2018-11-28 Eboard Meeting Notes
@jwflory will follow up with @jasoncarr0 to get a topic summary and then send the weekly email by tomorrow (11-29) 12PM.

Next week (12/7):
- Casual game night
- Maybe @ct-martin is able to get an additional projector?

**Comment by jrtechs** [comment] 2018-12-29 20:04
I'm going to close this issue and open a new one for spring.

**Closed by jrtechs** 2018-12-29 20:04 UTC
Labels: internal organization, meetings, priority:high, review at meeting
