### ISSUE TITLE
Follow up on April 2018 FOSS Family Outback dinner fundraising

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#10] opened 2017-10-02 20:45 UTC
# Summary

Organize a FOSS Family dinner at a restaurant where RITlug can partner to do a fundraiser.

# Explanation

Per tradition, there's always one or two FOSS Family dinners during the semester, where RITluggers and FOSS folk around the community go out for a night of dinner. Since RITlug is also trying to do some fundraising, we want to organize a dinner at a restaurant that will partner with us to contribute money to our club treasury.

# Options

There's a few options open to us. I wanted to check if some of our favorite spots might be willing to do this for us as a special occasion.

* **Available**:
    * Outback Steakhouse (15% return to RITlug)
    * The Wok (20% return to RITlug)
    * Deli Sandro’s (20% return to RITlug)
    * Amaya Indian Cuisine (20% return to RITlug)
* **Need to check**:
    * Peppermint’s (call??)
    * Fuego's (ask on next visit??)

**Comment by jflory7** [comment] 2017-10-22 18:51
Still need to follow up with Fuego. Looking at Sticky Lips for a sponsored meal in November for RITlug. I have options for Wednesday, Thursday, and Friday nights. I'm leaning towards choosing a Friday night in November.

**Comment by jflory7** [comment] 2017-12-15 22:41
We had a dinner, but we still want to do a fundraiser dinner next semester. Will revisit in spring.

**Comment by jflory7** [comment] 2018-03-31 18:59
@TaylorBowling is working on this for this semester. We are planning for Wednesday, April 18, 2018 at Outback Steakhouse. Outback will donate 15% of the final amount to RITlug if we bring in 20 or more people. This will help us with fundraising and will also give a chance to have a dinner before the looming end of finals approaches.

I will put out a "save the date" email on the FOSSRIT mailing list. More details to come.

**Comment by jflory7** [comment] 2018-04-15 17:04
@Tjzabel Let's keep it open until we have the donation processed and confirmed for inclusion in our club budget.

**Comment by Tjzabel** [comment] 2018-04-25 23:58
@jflory7 has our donation been processed?

**Comment by TaylorBowling** [comment] 2018-04-26 03:37
@jflory7 @Tjzabel Our donation has been processed, and is being mailed directly to our contact in the club office, who will deposit it into our account.

**Comment by jflory7** [comment] 2018-04-27 19:26
_Discussed in 2018-04-27 eboard meeting._

The work for this semester is done. We will follow up with this next semester to make sure the money is in our budget for the 2018-2019 academic year.

**Comment by ct-martin** [comment] 2018-09-07 06:11
@jwflory @jibby0 Please follow up with club office to see if there were issues with this going through. Based on the money I'm seeing in CampusGroups it appears that this might not have as the budget we have does not match the bracket of what SG says we should be allocated.

**Comment by ct-martin** [comment] 2018-09-07 06:12
@TaylorBowling please post in #eboard-alums on Slack with how much we should have gotten from the event and when we were told the payment was sent

**Comment by jwflory** [comment] 2018-09-07 14:28
I followed up with @TaylorBowling. From the GroupRaise platform dashboard, we raised $77.95.

![Screenshot of GroupRaise fundraising platform of our revenue from FOSS Dinner](https://user-images.githubusercontent.com/4721034/45224699-96cb4380-b288-11e8-823d-e501d946d934.png "Screenshot of GroupRaise fundraising platform of our revenue from FOSS Dinner")

Noting this, we should also dig up our records for the jackets and figure out how much we took in from those and raise an issue with the Clubs Office if we misunderstood the process this year.

**Comment by ct-martin** [comment] 2018-09-07 14:57
Given what I remember the ballpark for the jackets being, the numbers in
CampusGroups definitely doesn't match up.

--
Christian Martin (Phone)

**Comment by jwflory** [comment] 2018-09-09 16:36
To update, @jibby0 is meeting Clubs Office to discuss budget on Monday (tomorrow) at 3pm.

**Comment by jrtechs** [comment] 2018-09-10 20:56
Eboard Comment(9-10-18):
@jibby0 will out if outback sent check to RIT. Once we know if RIT received the check we will contact club office with guidance with SJ about our budget.

**Comment by icflournoy** [comment] 2018-09-24 21:18
### 2018-09-24 Eboard Meeting
#### Discussion
New check has been issued, should be received by RIT in 4-6 weeks.

#### Action Items
- Nothing until we receive the check
- @jibby0 to take on https://github.com/RITlug/tasks/issues/67 to follow up with clubs regarding budget allocation for the year, why it wasn't what we expected, and if this fundraising dinner check from last year affected this year's budget.

**Comment by jwflory** [comment] 2018-10-14 15:54
@jibby0 I was wondering, is there any way we are notified the check lands? Or how can we verify RIT receives the check? Do we actually have to go in to the clubs office and ask?

**Comment by ct-martin** [comment] 2018-10-14 16:32
In theory I would think it should appear on CampusGroups, but...

--
Christian Martin (Phone)

**Comment by jibby0** [comment] 2018-10-16 17:38
Yes, it should show up in CampusGroups. If it doesn't by early November (which gives them the est. 4-6 weeks) I'll follow up with Outback.

**Comment by jibby0** [comment] 2018-10-31 20:15
We're approaching the 6 week upper bound. If I don't see or hear anything by November 5th, I'll follow up with my Outback contact.

**Comment by jibby0** [comment] 2018-11-06 23:30
We've surpassed 6 weeks. CampusGroups has not shown any deposit from Outback. I'll reach out again this week.

**Comment by jwflory** [comment] 2018-11-19 15:35
@jibby0 Any word back yet?

**Comment by jibby0** [comment] 2018-11-19 15:57
Due to a mix up, no check was sent.

A check was sent with expedited shipping a few days ago. We should expect to see it early next week.

**Comment by Tjzabel** [comment] 2018-11-28 17:51
@jibby0 any progress?

**Comment by jibby0** [comment] 2018-11-28 19:20
@Tjzabel Nothing in CampusGroups, nothing new from outback. They said early this week. If i continue to hear nothing today, I'll reach out again.

**Comment by jibby0** [comment] 2018-12-05 14:39
Check has been received. Waiting on club office to process the check.

**Comment by Tjzabel** [comment] 2018-12-11 16:52
@jibby0 Check has now been processed, correct?

**Comment by Tjzabel** [comment] 2018-12-11 16:54
Monetary additions have not yet shown up in campusgroups. We should keep this open until that occurs.

**Comment by TaylorBowling** [comment] 2018-12-11 16:57
I approved the cashing of the check last week with Megan Brown from the
Center for Campus life. Let me know if I need to take any further action.

Thanks,
-Taylor

**Comment by jibby0** [comment] 2018-12-11 17:33
Thank you Taylor! I got the confirmation email: as of Dec 7th, the Outback check has been routed for deposit.

The money may not show up in campusgroups until after break. I'd call the confirmation email proof, but it may be best to wait until the money's in our hands, you're right.

**Comment by jibby0** [comment] 2019-01-17 20:39
:eyes:

I'm heading into club office soon to pick up an EAF, I'll check with them

**Comment by jibby0** [comment] 2019-01-23 15:54
I can confirm, the outback check was added as a credit, according to the transaction list in our club office folder.

Still not appearing in CampusGroups, however.

I feel we could close this: we have paper records now, showing club office as the money. Any money we use goes through them, so we have access to it.

Or we could keep waiting, and see if it appears on CampusGroups before closing this.

**Comment by ct-martin** [comment] 2019-01-23 16:49
I think we should wait until it's in CG given how smoothly this went

--
Christian Martin (Phone)

**Comment by Tjzabel** [comment] 2019-02-14 21:08
Stub is in our club folder. Closing issue as (finally) complete :+1:

**Closed by Tjzabel** 2019-02-14 21:08 UTC
Labels: blocked, events, priority:med
